### ISSUE TITLE
HTML from google drive via Zapier

### ISSUE THREAD

**Issue by CobSlinger** [htmlcsstoimage/docs#7]
Hi crew, I'm looking to set up a Zap using this app, where when I upload an HTML file to google drive, it automatically renders it into an image so I can then upload it to FB.

I've tried putting all kinds of things in the HTML field but can't seem to get it to work. I would have thought that the "File" option would have worked, but that just renders a long web address, which is probably a link to the file on Zapier rather than the file contents itself.

Is there a way to pass the file contents into the HTML field, or a way of using the embed links? I tried using `<div w3-include-html=EMBED_LINK></div>` but that just rendered a big white square! Any help is greatly appreciated!

**Comment by MallikarjunHt** [comment]
Use php file handling to solve the problem.

Mallikarjun H T

**Comment by mscoutermarsh** [comment]
@CobSlinger I gave this a try myself and it seems like it's not possible to pass the contents from drive as text.

Did you have any luck in figuring it out? I'm thinking you might need to use another zapier integration between drive and HCTI to do it.
